<a href="https://colab.research.google.com/github/macanoso/ciencia-datos-curso/blob/main/Tarea1/entrega_final.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
print("hola mundo")

hola mundo

In [2]:
import pandas as pd

df = pd.read_csv("/content/transacciones.csv")

In [3]:
df

       id       fecha        ciudad   categoria    metodo_pago   monto
0    1004  2024-01-01      Medellin   papeleria        tarjeta   73078
1    1079  2024-01-01          Cali  tecnologia       efectivo  110323
2    1067  2024-01-05  Barranquilla        aseo       efectivo  205064
3    1063  2024-01-06          Cali        aseo  transferencia   66135
4    1105  2024-01-06        Bogota        aseo       efectivo  210611
..    ...         ...           ...         ...            ...     ...
115  1003  2024-03-24   Bucaramanga   papeleria       efectivo  115056
116  1080  2024-03-24          Cali   papeleria        tarjeta  113329
117  1050  2024-03-26          Cali        aseo        tarjeta  101968
118  1078  2024-03-27      Medellin       hogar  transferencia   78733
119  1011  2024-03-28        Bogota       hogar  transferencia   46929

[120 rows x 6 columns]

In [4]:
df.groupby("ciudad")["monto"].sum()

ciudad
Barranquilla    7067912
Bogota          4750556
Bucaramanga     6822160
Cali            2335262
Medellin        3500221
Name: monto, dtype: int64